# .travis.yml

language: node_js
sudo: required
script: bash ./deploy.sh
branches:
  only:
  - source
node_js:
 - '6.1'
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - rvm install 2.1
  - rvm use 2.1
  - . $HOME/.nvm/nvm.sh && nvm install 6.1 && nvm use 6.1
  - gem install bundler
  - bundle check || bundle install
  - npm install mathjax-node-page
  - sudo apt-get install moreutils
env:
  global:
  - ENCRYPTION_LABEL: "00bfb4d57df6"
  - COMMIT_AUTHOR_EMAIL: "p.krautzberger@gmail.com"
